services:
  samba:
    image: dockurr/samba
    container_name: samba
    network_mode: host
    environment:
      UID: "1000"
      GID: "1000"
      NAME: "data"
      USER: ${USER}
      PASS: ${PASS}
    # ports:
    #   - 445:445
    volumes:
      - /home/rui/data:/storage
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Only update this container if the label is set