services:
  jdownloader:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Lisbon
      DARK_MODE: 1
      WEB_FILE_MANAGER: 1
      WEB_FILE_MANAGER_ALLOWED_PATHS: /output
    volumes:
      - ./config:/config
      - /home/rui/data/downloads:/output # <--- Maps to your download folder
    # ports:
    #   - 5800:5800 # The Web Interface
    restart: unless-stopped
    networks:
      - default_network
  
networks:
  default_network:
    external: true