services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment:
      PUID: 1000
      PGID: 988
      HOMEPAGE_ALLOWED_HOSTS: ubuntu-server:3000,dashboard.home # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    restart: unless-stopped

networks:
  default:
    name: default_network
    external: true
