services:
  # 1. THE WORKER
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000   # Your 'rui' user
      - PGID=1000
      - TZ=Europe/Lisbon
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      # MAP THE FULL DATA FOLDER (Matches Copyparty)
      - /home/rui/data:/data
    ports:
      # - 8080:8080   # Web UI
      - 6881:6881   # Torrent traffic (TCP)
      - 6881:6881/udp # Torrent traffic (UDP)
    restart: unless-stopped
    networks:
      - default_network

  # 2. THE MANAGER (Movies)
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./radarr/config:/config
      # MUST BE IDENTICAL to qBittorrent
      - /home/rui/data:/data
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    networks:
      - default_network

  # 3. THE SCOUT (Indexers)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./prowlarr/config:/config
      # Prowlarr doesn't need access to media files, just config
    # ports:
    #   - 9696:9696
    restart: unless-stopped
    networks:
      - default_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./sonarr/config:/config
      - /home/rui/data:/data
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    networks:
      - default_network

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ./lidarr/config:/config
      - /home/rui/data:/data
    # ports:
    #   - 8686:8686
    restart: unless-stopped
    networks:
      - default_network

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Lisbon
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - default_network

networks:
  default_network:
    external: true