services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    # ports:
    #   - 9443:9443
    #   - 9000:9000
    labels:
      - com.centurylinklabs.watchtower.enable=true # Only update this container if the label is set
networks:
  default:
    name: default_network
    external: true
