---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Control Group:
    - Homepage Container:
        icon: homepage.png
        href: "http://dashboard.home"
        description: "Dashboard Control Center"
        server: my-docker  
        container: homepage      
        showStats: true          
    
    - Dockge:
        icon: dockge.svg
        href: "http://dockge.home"
        description: "Docker Management Center"
        server: my-docker  
        container: dockge      
        showStats: true   

    - Portainer:
        icon: portainer.svg
        href: "http://portainer.home"
        description: "Docker Management Center but with a suit"
        server: my-docker
        container: portainer
        showStats: true
        widget:
            type: portainer
            url: "https://portainer:9443"
            env: 3
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}

    - Tailscale:
        icon: tailscale.svg
        href: "https://login.tailscale.com/admin/machines"
        description: "Tailwi... i mean... Tailscale"
        widget:
            type: tailscale
            deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICEID}}
            key: {{HOMEPAGE_VAR_TAILSCALE_KEY}}


- Network Group:
    - Pi-hole:
        icon: pi-hole.svg
        href: "http://pihole.home/admin"
        description: "The DNS sink with a hole"
        server: my-docker
        container: pihole
        showStats: true
        widget:
            type: pihole
            url: http://pihole
            version: 6 # required if running v6 or higher, defaults to 5
            key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}" # optional, in v6 can be your password or app password

    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.svg
        href: "http://npm.home:81"
        description: "Reverse proxy with a big name"
        server: my-docker
        container: nginx-proxy-manager
        showStats: true
        widget:
            type: npm
            url: http://nginx-proxy-manager:81
            username: {{HOMEPAGE_VAR_NPM_USER}}
            password: {{HOMEPAGE_VAR_NPM_PASSWORD}}
    
- Other Services:
    - Copyparty:
        icon: copyparty.svg
        href: "http://copyparty.home"
        description: "It's a party!"
        server: my-docker
        container: copyparty
        showStats: true
    
    - Jellyfin:
        icon: jellyfin.svg
        href: "http://jellyfin.home"
        description: "For gelatinous media"
        server: my-docker
        container: jellyfin
        showStats: true
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_KEY}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            enableMediaControl: true # optional, defaults to true
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: true # optional, defaults to true

    - immich:
        icon: immich.svg
        href: "http://immich.home"
        description: "So we german now?"
        server: my-docker
        container: immich_server
        showStats: true
        widget:
            type: immich
            url: http://immich_server:2283
            key: {{HOMEPAGE_VAR_IMMICH_KEY}}
            version: 2

- "*Arrs Group":
    - qBittorrent:
        icon: qbittorrent.svg
        href: "http://qbittorrent.home"
        description: "The ol' faithful"
        server: my-docker
        container: qbittorrent
        showStats: true
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: {{HOMEPAGE_VAR_QBITTORRENT_USER}}
            password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
            enableLeechProgress: true # optional, defaults to false
            enableLeechSize: true # optional, defaults to false

    - Radarr:
        icon: radarr.svg
        href: "http://radarr.home"
        description: "ping... ping..."
        server: my-docker
        container: radarr
        showStats: true
        widget:
            type: radarr
            url: http://radarr:7878
            key: {{HOMEPAGE_VAR_RADARR_KEY}}

    - Prowlarr:
        icon: prowlarr.svg
        href: "http://prowlarr.home"
        description: "The tiger is cute tho"
        server: my-docker
        container: prowlarr
        showStats: true
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: {{HOMEPAGE_VAR_PROWLARR_KEY}}

    - Sonarr:
        icon: sonarr.svg
        href: "http://sonarr.home"
        description: "Like radarr but with more anime"
        server: my-docker
        container: sonarr
        showStats: true
        widget:
            type: sonarr
            url: http://sonarr:8989
            key: {{HOMEPAGE_VAR_SONARR_KEY}}

    - Lidarr:
        icon: lidarr.svg
        href: "http://lidarr.home"
        description: "Fucking music nerd... go outside"
        server: my-docker
        container: lidarr
        showStats: true
        widget:
            type: lidarr
            url: http://lidarr:8686
            key: {{HOMEPAGE_VAR_LIDARR_KEY}}

    - Bazarr:
        icon: bazarr.svg
        href: "http://bazarr.home"
        description: "lemme sub that title"
        server: my-docker
        container: bazarr
        showStats: true
        widget:
            type: bazarr
            url: http://bazarr:6767
            key: {{HOMEPAGE_VAR_BAZARR_KEY}}