---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

background:
  image: https://raw.githubusercontent.com/orangci/walls-catppuccin-mocha/master/dark-waves.jpg
  # blur: sm
 
cardBlur: xl

color: neutral

layout:
  Control Group:
    style: column
  Network Group:
    style: column
  Other Services:
    style: column
  "*Arrs Group":
    style: row
    columns: 4

headerStyle: boxed
